[mypy]
plugins = mypy_django_plugin.main, mypy_drf_plugin.main
python_version = 3.14
strict = True
mypy_path = backend
exclude = migrations/

[mypy.plugins.django-stubs]
django_settings_module = config.settings.local

[mypy-environ.*]
ignore_missing_imports = True
