#!/usr/bin/env bash
# Read-only "opening ceremony" environment check. Never mutates state —
# only reports. Run automatically at SessionStart, or on demand via the
# /dev-check skill.
set -uo pipefail

warn_count=0
fail_count=0

pass() { printf '  [ok]   %s\n' "$1"; }
warn() { printf '  [warn] %s\n' "$1"; warn_count=$((warn_count + 1)); }
fail() { printf '  [fail] %s\n' "$1"; fail_count=$((fail_count + 1)); }
section() { printf '\n== %s ==\n' "$1"; }

echo "=== Riser environment check (read-only) ==="

section "Toolchain"
if command -v uv >/dev/null 2>&1; then
  pass "uv installed ($(uv --version))"
else
  fail "uv not found — install: curl -LsSf https://astral.sh/uv/install.sh | sh"
fi

if command -v node >/dev/null 2>&1; then
  node_version="$(node --version)"
  if [ -f frontend/.nvmrc ]; then
    expected="v$(cat frontend/.nvmrc)"
    if [ "$node_version" = "$expected" ]; then
      pass "node $node_version matches frontend/.nvmrc"
    else
      warn "node $node_version != frontend/.nvmrc ($expected) — consider: nvm use"
    fi
  else
    pass "node installed ($node_version)"
  fi
else
  fail "node not found — install via nvm: https://github.com/nvm-sh/nvm"
fi

if command -v npm >/dev/null 2>&1; then
  pass "npm installed ($(npm --version))"
else
  fail "npm not found"
fi

section "Backend environment"
if [ -f backend/pyproject.toml ]; then
  if [ ! -d backend/.venv ]; then
    warn "backend/.venv missing — run: uv sync --project backend"
  elif command -v uv >/dev/null 2>&1; then
    if (cd backend && uv sync --locked --dry-run) >/dev/null 2>&1; then
      pass "backend dependencies in sync with uv.lock"
    else
      warn "backend deps out of sync — run: uv sync --project backend"
    fi
  fi
else
  warn "backend/pyproject.toml not found yet — backend not scaffolded"
fi

section "Frontend environment"
if [ -f frontend/package.json ]; then
  if [ -d frontend/node_modules ]; then
    if [ frontend/package-lock.json -nt frontend/node_modules ]; then
      warn "frontend/package-lock.json is newer than node_modules — run: npm --prefix frontend ci"
    else
      pass "frontend/node_modules present and appears current"
    fi
  else
    warn "frontend/node_modules missing — run: npm --prefix frontend ci"
  fi
else
  warn "frontend/package.json not found yet — frontend not scaffolded"
fi

section "Env files"
for dir in backend frontend; do
  if [ -f "$dir/.env.example" ] && [ ! -f "$dir/.env" ]; then
    warn "$dir/.env missing — copy from $dir/.env.example and fill in secrets"
  fi
done

section "Git hooks"
if command -v pre-commit >/dev/null 2>&1; then
  pass "pre-commit installed ($(pre-commit --version))"
  for stage in pre-commit pre-push commit-msg; do
    if [ -f ".git/hooks/$stage" ] && grep -q "File generated by pre-commit" ".git/hooks/$stage" 2>/dev/null; then
      pass "git hook installed: $stage"
    else
      warn "git hook missing: $stage — run: pre-commit install --install-hooks -t pre-commit -t pre-push -t commit-msg"
    fi
  done
else
  fail "pre-commit CLI not found — install: uv tool install pre-commit"
fi

section "GitHub CLI"
if command -v gh >/dev/null 2>&1; then
  if gh auth status >/dev/null 2>&1; then
    pass "gh authenticated"
  else
    warn "gh installed but not authenticated — run: gh auth login"
  fi
else
  warn "gh CLI not found — install: https://cli.github.com"
fi

section "Git branch"
branch="$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo unknown)"
echo "  current branch: $branch"
if [ "$branch" = "main" ]; then
  warn "you're on main — create a feature branch before making changes"
fi
if git remote get-url origin >/dev/null 2>&1; then
  ahead_behind="$(git rev-list --left-right --count origin/main...HEAD 2>/dev/null || echo 'unknown')"
  echo "  origin/main ahead/behind (behind ahead): $ahead_behind"
else
  echo "  (no 'origin' remote configured yet)"
fi

echo
printf 'SUMMARY: %d warning(s), %d failure(s)\n' "$warn_count" "$fail_count"
exit 0
