# Generated by Django 6.0.7 on 2026-07-19 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Elevator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("device_identifier", models.CharField(max_length=100)),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("CAT1", "Category 1 (Annual)"),
                            ("CAT5", "Category 5 (Five-Year)"),
                        ],
                        max_length=4,
                    ),
                ),
                ("last_inspection_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="elevators",
                        to="compliance.building",
                    ),
                ),
            ],
            options={
                "ordering": ["device_identifier"],
            },
        ),
    ]
