# Generated by Django 6.0.7 on 2026-07-27 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("compliance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="bin",
            field=models.CharField(
                blank=True,
                help_text="Cached NYC Building Identification Number, resolved via DOB lookup.",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="elevator",
            name="dob_device_number",
            field=models.CharField(
                blank=True,
                help_text="Raw DOB device_number, when this row originated from a DOB lookup.",
                max_length=20,
                null=True,
            ),
        ),
    ]
